version: '3.7'

services:
 app:
  container_name: app
  build:
    context: ./app
    dockerfile: Dockerfile
  entrypoint: ["tail", "-f", "/dev/null"]
  volumes:
    - './app:/app'
  environment:
      - CASSANDRA_IP_ADDRESS=172.28.1.3
      - CASSANDRA_KEYSPACE=roy
  depends_on:
    - cas1
  networks:
    testing_net:
        ipv4_address: 172.28.1.1

 cas1:
    container_name: cas1
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    networks:
      testing_net:
          ipv4_address: 172.28.1.2

 cas2:
  container_name: cas2
  image: cassandra:latest
  ports:
      - 9043:9042
  depends_on:
    - cas1
  environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=cas1
  networks:
      testing_net:
          ipv4_address: 172.28.1.3


networks:
  testing_net:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16
